// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/anduril/lattice-sdk-go/core"
	entities "github.com/anduril/lattice-sdk-go/entities"
	internal "github.com/anduril/lattice-sdk-go/internal"
	objects "github.com/anduril/lattice-sdk-go/objects"
	option "github.com/anduril/lattice-sdk-go/option"
	tasks "github.com/anduril/lattice-sdk-go/tasks"
)

type Client struct {
	Entities *entities.Client
	Tasks    *tasks.Client
	Objects  *objects.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Entities: entities.NewClient(options),
		Tasks:    tasks.NewClient(options),
		Objects:  objects.NewClient(options),
		options:  options,
		baseURL:  options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
