// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/anduril/lattice-sdk-go/v2/core"
	entities "github.com/anduril/lattice-sdk-go/v2/entities"
	internal "github.com/anduril/lattice-sdk-go/v2/internal"
	objects "github.com/anduril/lattice-sdk-go/v2/objects"
	option "github.com/anduril/lattice-sdk-go/v2/option"
	tasking "github.com/anduril/lattice-sdk-go/v2/tasking"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Entities *entities.Client
	Tasking  *tasking.Client
	Objects  *objects.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:   options.ToHeader(),
		Entities: entities.NewClient(opts...),
		Tasking:  tasking.NewClient(opts...),
		Objects:  objects.NewClient(opts...),
	}
}
