// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/anduril/lattice-sdk-go/core"
	entities "github.com/anduril/lattice-sdk-go/entities"
	internal "github.com/anduril/lattice-sdk-go/internal"
	objects "github.com/anduril/lattice-sdk-go/objects"
	option "github.com/anduril/lattice-sdk-go/option"
	tasks "github.com/anduril/lattice-sdk-go/tasks"
	http "net/http"
)

type Client struct {
	Entities *entities.Client
	Tasks    *tasks.Client
	Objects  *objects.Client

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Entities: entities.NewClient(opts...),
		Tasks:    tasks.NewClient(opts...),
		Objects:  objects.NewClient(opts...),
		baseURL:  options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}
