// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: anduril/auth/v2/idp.pub.proto

package authv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSSOURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The email address of the user wishing to authenticate.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// The URL that the user should be redirected to after they successfully authenticate.
	RedirectUrl string `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	// If true, appends the token to the query params when redirecting to redirect_url. Only for OIDC.
	AppendToken bool `protobuf:"varint,3,opt,name=append_token,json=appendToken,proto3" json:"append_token,omitempty"`
}

func (x *GetSSOURLRequest) Reset() {
	*x = GetSSOURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSSOURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSSOURLRequest) ProtoMessage() {}

func (x *GetSSOURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSSOURLRequest.ProtoReflect.Descriptor instead.
func (*GetSSOURLRequest) Descriptor() ([]byte, []int) {
	return file_anduril_auth_v2_idp_pub_proto_rawDescGZIP(), []int{0}
}

func (x *GetSSOURLRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetSSOURLRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *GetSSOURLRequest) GetAppendToken() bool {
	if x != nil {
		return x.AppendToken
	}
	return false
}

type GetSSOURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*GetSSOURLResponse_InvalidEmail_
	//	*GetSSOURLResponse_ValidDomain_
	Response isGetSSOURLResponse_Response `protobuf_oneof:"response"`
}

func (x *GetSSOURLResponse) Reset() {
	*x = GetSSOURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSSOURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSSOURLResponse) ProtoMessage() {}

func (x *GetSSOURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSSOURLResponse.ProtoReflect.Descriptor instead.
func (*GetSSOURLResponse) Descriptor() ([]byte, []int) {
	return file_anduril_auth_v2_idp_pub_proto_rawDescGZIP(), []int{1}
}

func (m *GetSSOURLResponse) GetResponse() isGetSSOURLResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GetSSOURLResponse) GetInvalidEmail() *GetSSOURLResponse_InvalidEmail {
	if x, ok := x.GetResponse().(*GetSSOURLResponse_InvalidEmail_); ok {
		return x.InvalidEmail
	}
	return nil
}

func (x *GetSSOURLResponse) GetValidDomain() *GetSSOURLResponse_ValidDomain {
	if x, ok := x.GetResponse().(*GetSSOURLResponse_ValidDomain_); ok {
		return x.ValidDomain
	}
	return nil
}

type isGetSSOURLResponse_Response interface {
	isGetSSOURLResponse_Response()
}

type GetSSOURLResponse_InvalidEmail_ struct {
	InvalidEmail *GetSSOURLResponse_InvalidEmail `protobuf:"bytes,1,opt,name=invalid_email,json=invalidEmail,proto3,oneof"`
}

type GetSSOURLResponse_ValidDomain_ struct {
	ValidDomain *GetSSOURLResponse_ValidDomain `protobuf:"bytes,2,opt,name=valid_domain,json=validDomain,proto3,oneof"`
}

func (*GetSSOURLResponse_InvalidEmail_) isGetSSOURLResponse_Response() {}

func (*GetSSOURLResponse_ValidDomain_) isGetSSOURLResponse_Response() {}

// A wrapper around the types of supported IDPs.
type Idp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Idp:
	//
	//	*Idp_Internal
	//	*Idp_External
	//	*Idp_Piv
	Idp isIdp_Idp `protobuf_oneof:"idp"`
}

func (x *Idp) Reset() {
	*x = Idp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Idp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idp) ProtoMessage() {}

func (x *Idp) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idp.ProtoReflect.Descriptor instead.
func (*Idp) Descriptor() ([]byte, []int) {
	return file_anduril_auth_v2_idp_pub_proto_rawDescGZIP(), []int{2}
}

func (m *Idp) GetIdp() isIdp_Idp {
	if m != nil {
		return m.Idp
	}
	return nil
}

func (x *Idp) GetInternal() *InternalIDP {
	if x, ok := x.GetIdp().(*Idp_Internal); ok {
		return x.Internal
	}
	return nil
}

func (x *Idp) GetExternal() *ExternalIDP {
	if x, ok := x.GetIdp().(*Idp_External); ok {
		return x.External
	}
	return nil
}

func (x *Idp) GetPiv() *PIV {
	if x, ok := x.GetIdp().(*Idp_Piv); ok {
		return x.Piv
	}
	return nil
}

type isIdp_Idp interface {
	isIdp_Idp()
}

type Idp_Internal struct {
	Internal *InternalIDP `protobuf:"bytes,1,opt,name=internal,proto3,oneof"`
}

type Idp_External struct {
	External *ExternalIDP `protobuf:"bytes,2,opt,name=external,proto3,oneof"`
}

type Idp_Piv struct {
	Piv *PIV `protobuf:"bytes,3,opt,name=piv,proto3,oneof"`
}

func (*Idp_Internal) isIdp_Idp() {}

func (*Idp_External) isIdp_Idp() {}

func (*Idp_Piv) isIdp_Idp() {}

// A message indicating that the user may login with the internal IDP.
type InternalIDP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InternalIDP) Reset() {
	*x = InternalIDP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalIDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalIDP) ProtoMessage() {}

func (x *InternalIDP) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalIDP.ProtoReflect.Descriptor instead.
func (*InternalIDP) Descriptor() ([]byte, []int) {
	return file_anduril_auth_v2_idp_pub_proto_rawDescGZIP(), []int{3}
}

// A message indicating that a user may login with an external IDP.
type ExternalIDP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A human-readable name for the IDP.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The single sign on URL that the user may be redirected to to authenticate.
	SsoUrl string `protobuf:"bytes,2,opt,name=sso_url,json=ssoUrl,proto3" json:"sso_url,omitempty"`
	// String that uniquely identified the same IDP across different instances
	UniqueId string `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
}

func (x *ExternalIDP) Reset() {
	*x = ExternalIDP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalIDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalIDP) ProtoMessage() {}

func (x *ExternalIDP) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalIDP.ProtoReflect.Descriptor instead.
func (*ExternalIDP) Descriptor() ([]byte, []int) {
	return file_anduril_auth_v2_idp_pub_proto_rawDescGZIP(), []int{4}
}

func (x *ExternalIDP) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalIDP) GetSsoUrl() string {
	if x != nil {
		return x.SsoUrl
	}
	return ""
}

func (x *ExternalIDP) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

// A message indicating that the user may login using their PIV smart card.
type PIV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PIV) Reset() {
	*x = PIV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PIV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PIV) ProtoMessage() {}

func (x *PIV) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PIV.ProtoReflect.Descriptor instead.
func (*PIV) Descriptor() ([]byte, []int) {
	return file_anduril_auth_v2_idp_pub_proto_rawDescGZIP(), []int{5}
}

// The given email was invalid or not registered.
type GetSSOURLResponse_InvalidEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A human-readable reason (that may be shown to the user).
	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *GetSSOURLResponse_InvalidEmail) Reset() {
	*x = GetSSOURLResponse_InvalidEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSSOURLResponse_InvalidEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSSOURLResponse_InvalidEmail) ProtoMessage() {}

func (x *GetSSOURLResponse_InvalidEmail) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSSOURLResponse_InvalidEmail.ProtoReflect.Descriptor instead.
func (*GetSSOURLResponse_InvalidEmail) Descriptor() ([]byte, []int) {
	return file_anduril_auth_v2_idp_pub_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetSSOURLResponse_InvalidEmail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// The given email domain is recognized, and the user may sign in using the specified IDPs.
type GetSSOURLResponse_ValidDomain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idps []*Idp `protobuf:"bytes,1,rep,name=idps,proto3" json:"idps,omitempty"`
}

func (x *GetSSOURLResponse_ValidDomain) Reset() {
	*x = GetSSOURLResponse_ValidDomain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSSOURLResponse_ValidDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSSOURLResponse_ValidDomain) ProtoMessage() {}

func (x *GetSSOURLResponse_ValidDomain) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_auth_v2_idp_pub_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSSOURLResponse_ValidDomain.ProtoReflect.Descriptor instead.
func (*GetSSOURLResponse_ValidDomain) Descriptor() ([]byte, []int) {
	return file_anduril_auth_v2_idp_pub_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetSSOURLResponse_ValidDomain) GetIdps() []*Idp {
	if x != nil {
		return x.Idps
	}
	return nil
}

var File_anduril_auth_v2_idp_pub_proto protoreflect.FileDescriptor

var file_anduril_auth_v2_idp_pub_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76,
	0x32, 0x2f, 0x69, 0x64, 0x70, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x32,
	0x22, 0x6e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x53, 0x4f, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0xad, 0x02, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x53, 0x4f, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x32, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x53, 0x4f, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x48, 0x00,
	0x52, 0x0c, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x53,
	0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x53, 0x4f, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x1a, 0x26, 0x0a, 0x0c, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x37, 0x0a, 0x0b, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x69, 0x64,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x6e, 0x64, 0x75, 0x72,
	0x69, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x64, 0x70, 0x52, 0x04,
	0x69, 0x64, 0x70, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0xae, 0x01, 0x0a, 0x03, 0x49, 0x64, 0x70, 0x12, 0x3a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x6e, 0x64,
	0x75, 0x72, 0x69, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x50, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x12, 0x3a, 0x0a, 0x08, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x49, 0x44, 0x50, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x12, 0x28, 0x0a, 0x03, 0x70, 0x69, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x32, 0x2e,
	0x50, 0x49, 0x56, 0x48, 0x00, 0x52, 0x03, 0x70, 0x69, 0x76, 0x42, 0x05, 0x0a, 0x03, 0x69, 0x64,
	0x70, 0x22, 0x0d, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x50,
	0x22, 0x57, 0x0a, 0x0b, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x50, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x73, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x73, 0x6f, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x22, 0x05, 0x0a, 0x03, 0x50, 0x49, 0x56,
	0x32, 0x5a, 0x0a, 0x04, 0x49, 0x64, 0x70, 0x73, 0x12, 0x52, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53,
	0x53, 0x4f, 0x55, 0x52, 0x4c, 0x12, 0x21, 0x2e, 0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x53, 0x4f, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x6e, 0x64, 0x75, 0x72,
	0x69, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x53,
	0x4f, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xba, 0x01, 0x0a,
	0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x32, 0x42, 0x0b, 0x49, 0x64, 0x70, 0x50, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2f, 0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2d,
	0x67, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x2f, 0x76, 0x32, 0x3b, 0x61, 0x75, 0x74, 0x68, 0x76, 0x32, 0xa2, 0x02, 0x03,
	0x41, 0x41, 0x58, 0xaa, 0x02, 0x0f, 0x41, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x2e, 0x56, 0x32, 0xca, 0x02, 0x0f, 0x41, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x5c,
	0x41, 0x75, 0x74, 0x68, 0x5c, 0x56, 0x32, 0xe2, 0x02, 0x1b, 0x41, 0x6e, 0x64, 0x75, 0x72, 0x69,
	0x6c, 0x5c, 0x41, 0x75, 0x74, 0x68, 0x5c, 0x56, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x41, 0x6e, 0x64, 0x75, 0x72, 0x69, 0x6c, 0x3a,
	0x3a, 0x41, 0x75, 0x74, 0x68, 0x3a, 0x3a, 0x56, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_anduril_auth_v2_idp_pub_proto_rawDescOnce sync.Once
	file_anduril_auth_v2_idp_pub_proto_rawDescData = file_anduril_auth_v2_idp_pub_proto_rawDesc
)

func file_anduril_auth_v2_idp_pub_proto_rawDescGZIP() []byte {
	file_anduril_auth_v2_idp_pub_proto_rawDescOnce.Do(func() {
		file_anduril_auth_v2_idp_pub_proto_rawDescData = protoimpl.X.CompressGZIP(file_anduril_auth_v2_idp_pub_proto_rawDescData)
	})
	return file_anduril_auth_v2_idp_pub_proto_rawDescData
}

var file_anduril_auth_v2_idp_pub_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_anduril_auth_v2_idp_pub_proto_goTypes = []any{
	(*GetSSOURLRequest)(nil),               // 0: anduril.auth.v2.GetSSOURLRequest
	(*GetSSOURLResponse)(nil),              // 1: anduril.auth.v2.GetSSOURLResponse
	(*Idp)(nil),                            // 2: anduril.auth.v2.Idp
	(*InternalIDP)(nil),                    // 3: anduril.auth.v2.InternalIDP
	(*ExternalIDP)(nil),                    // 4: anduril.auth.v2.ExternalIDP
	(*PIV)(nil),                            // 5: anduril.auth.v2.PIV
	(*GetSSOURLResponse_InvalidEmail)(nil), // 6: anduril.auth.v2.GetSSOURLResponse.InvalidEmail
	(*GetSSOURLResponse_ValidDomain)(nil),  // 7: anduril.auth.v2.GetSSOURLResponse.ValidDomain
}
var file_anduril_auth_v2_idp_pub_proto_depIdxs = []int32{
	6, // 0: anduril.auth.v2.GetSSOURLResponse.invalid_email:type_name -> anduril.auth.v2.GetSSOURLResponse.InvalidEmail
	7, // 1: anduril.auth.v2.GetSSOURLResponse.valid_domain:type_name -> anduril.auth.v2.GetSSOURLResponse.ValidDomain
	3, // 2: anduril.auth.v2.Idp.internal:type_name -> anduril.auth.v2.InternalIDP
	4, // 3: anduril.auth.v2.Idp.external:type_name -> anduril.auth.v2.ExternalIDP
	5, // 4: anduril.auth.v2.Idp.piv:type_name -> anduril.auth.v2.PIV
	2, // 5: anduril.auth.v2.GetSSOURLResponse.ValidDomain.idps:type_name -> anduril.auth.v2.Idp
	0, // 6: anduril.auth.v2.Idps.GetSSOURL:input_type -> anduril.auth.v2.GetSSOURLRequest
	1, // 7: anduril.auth.v2.Idps.GetSSOURL:output_type -> anduril.auth.v2.GetSSOURLResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_anduril_auth_v2_idp_pub_proto_init() }
func file_anduril_auth_v2_idp_pub_proto_init() {
	if File_anduril_auth_v2_idp_pub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_anduril_auth_v2_idp_pub_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetSSOURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anduril_auth_v2_idp_pub_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetSSOURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anduril_auth_v2_idp_pub_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Idp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anduril_auth_v2_idp_pub_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*InternalIDP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anduril_auth_v2_idp_pub_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ExternalIDP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anduril_auth_v2_idp_pub_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PIV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anduril_auth_v2_idp_pub_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetSSOURLResponse_InvalidEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anduril_auth_v2_idp_pub_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetSSOURLResponse_ValidDomain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_anduril_auth_v2_idp_pub_proto_msgTypes[1].OneofWrappers = []any{
		(*GetSSOURLResponse_InvalidEmail_)(nil),
		(*GetSSOURLResponse_ValidDomain_)(nil),
	}
	file_anduril_auth_v2_idp_pub_proto_msgTypes[2].OneofWrappers = []any{
		(*Idp_Internal)(nil),
		(*Idp_External)(nil),
		(*Idp_Piv)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_anduril_auth_v2_idp_pub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anduril_auth_v2_idp_pub_proto_goTypes,
		DependencyIndexes: file_anduril_auth_v2_idp_pub_proto_depIdxs,
		MessageInfos:      file_anduril_auth_v2_idp_pub_proto_msgTypes,
	}.Build()
	File_anduril_auth_v2_idp_pub_proto = out.File
	file_anduril_auth_v2_idp_pub_proto_rawDesc = nil
	file_anduril_auth_v2_idp_pub_proto_goTypes = nil
	file_anduril_auth_v2_idp_pub_proto_depIdxs = nil
}
