// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: anduril/auth/v2/tokens.pub.proto

package authv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tokens_RefreshOidcTokens_FullMethodName = "/anduril.auth.v2.Tokens/RefreshOidcTokens"
)

// TokensClient is the client API for Tokens service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokensClient interface {
	// RefreshSessionToken attempts to retrieve new OIDC tokens from a user's refresh token. May also return a new
	// refresh_token with which future RefreshOidcTokens requests should use
	RefreshOidcTokens(ctx context.Context, in *RefreshOidcTokensRequest, opts ...grpc.CallOption) (*RefreshOidcTokensResponse, error)
}

type tokensClient struct {
	cc grpc.ClientConnInterface
}

func NewTokensClient(cc grpc.ClientConnInterface) TokensClient {
	return &tokensClient{cc}
}

func (c *tokensClient) RefreshOidcTokens(ctx context.Context, in *RefreshOidcTokensRequest, opts ...grpc.CallOption) (*RefreshOidcTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshOidcTokensResponse)
	err := c.cc.Invoke(ctx, Tokens_RefreshOidcTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokensServer is the server API for Tokens service.
// All implementations must embed UnimplementedTokensServer
// for forward compatibility.
type TokensServer interface {
	// RefreshSessionToken attempts to retrieve new OIDC tokens from a user's refresh token. May also return a new
	// refresh_token with which future RefreshOidcTokens requests should use
	RefreshOidcTokens(context.Context, *RefreshOidcTokensRequest) (*RefreshOidcTokensResponse, error)
	mustEmbedUnimplementedTokensServer()
}

// UnimplementedTokensServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokensServer struct{}

func (UnimplementedTokensServer) RefreshOidcTokens(context.Context, *RefreshOidcTokensRequest) (*RefreshOidcTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshOidcTokens not implemented")
}
func (UnimplementedTokensServer) mustEmbedUnimplementedTokensServer() {}
func (UnimplementedTokensServer) testEmbeddedByValue()                {}

// UnsafeTokensServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokensServer will
// result in compilation errors.
type UnsafeTokensServer interface {
	mustEmbedUnimplementedTokensServer()
}

func RegisterTokensServer(s grpc.ServiceRegistrar, srv TokensServer) {
	// If the following call pancis, it indicates UnimplementedTokensServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tokens_ServiceDesc, srv)
}

func _Tokens_RefreshOidcTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshOidcTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokensServer).RefreshOidcTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tokens_RefreshOidcTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokensServer).RefreshOidcTokens(ctx, req.(*RefreshOidcTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tokens_ServiceDesc is the grpc.ServiceDesc for Tokens service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tokens_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anduril.auth.v2.Tokens",
	HandlerType: (*TokensServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshOidcTokens",
			Handler:    _Tokens_RefreshOidcTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anduril/auth/v2/tokens.pub.proto",
}
