// Code generated by Fern. DO NOT EDIT.

package video_video_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	client "github.com/anduril/lattice-sdk-go/v4/client"
	option "github.com/anduril/lattice-sdk-go/v4/option"
	video "github.com/anduril/lattice-sdk-go/v4/video"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestVideoVideoListEgressStreamsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithClientCredentials("test_client_id", "test_client_secret"),
	)
	request := &video.ListEgressStreamsRequest{}
	_, invocationErr := client.Video.Video.ListEgressStreams(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVideoVideoListEgressStreamsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVideoVideoListEgressStreamsWithWireMock", "GET", "/api/v1/video/egress_streams", nil, 1)
}

func TestVideoVideoCreateEgressStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithClientCredentials("test_client_id", "test_client_secret"),
	)
	request := &video.CreateEgressStreamRequest{}
	_, invocationErr := client.Video.Video.CreateEgressStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVideoVideoCreateEgressStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVideoVideoCreateEgressStreamWithWireMock", "POST", "/api/v1/video/egress_streams", nil, 1)
}

func TestVideoVideoGetEgressStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithClientCredentials("test_client_id", "test_client_secret"),
	)
	request := &video.GetEgressStreamRequest{
		EgressID: "egressId",
	}
	_, invocationErr := client.Video.Video.GetEgressStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVideoVideoGetEgressStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVideoVideoGetEgressStreamWithWireMock", "GET", "/api/v1/video/egress_streams/egressId", nil, 1)
}

func TestVideoVideoDeleteEgressStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithClientCredentials("test_client_id", "test_client_secret"),
	)
	request := &video.DeleteEgressStreamRequest{
		EgressID: "egressId",
	}
	_, invocationErr := client.Video.Video.DeleteEgressStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVideoVideoDeleteEgressStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVideoVideoDeleteEgressStreamWithWireMock", "DELETE", "/api/v1/video/egress_streams/egressId", nil, 1)
}

func TestVideoVideoListIngressStreamsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithClientCredentials("test_client_id", "test_client_secret"),
	)
	request := &video.ListIngressStreamsRequest{}
	_, invocationErr := client.Video.Video.ListIngressStreams(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVideoVideoListIngressStreamsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVideoVideoListIngressStreamsWithWireMock", "GET", "/api/v1/video/ingress_streams", nil, 1)
}

func TestVideoVideoCreateIngressStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithClientCredentials("test_client_id", "test_client_secret"),
	)
	request := &video.CreateIngressStreamRequest{}
	_, invocationErr := client.Video.Video.CreateIngressStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVideoVideoCreateIngressStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVideoVideoCreateIngressStreamWithWireMock", "POST", "/api/v1/video/ingress_streams", nil, 1)
}

func TestVideoVideoGetIngressStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithClientCredentials("test_client_id", "test_client_secret"),
	)
	request := &video.GetIngressStreamRequest{
		IngressID: "ingressId",
	}
	_, invocationErr := client.Video.Video.GetIngressStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVideoVideoGetIngressStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVideoVideoGetIngressStreamWithWireMock", "GET", "/api/v1/video/ingress_streams/ingressId", nil, 1)
}

func TestVideoVideoDeleteIngressStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithClientCredentials("test_client_id", "test_client_secret"),
	)
	request := &video.DeleteIngressStreamRequest{
		IngressID: "ingressId",
	}
	_, invocationErr := client.Video.Video.DeleteIngressStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVideoVideoDeleteIngressStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVideoVideoDeleteIngressStreamWithWireMock", "DELETE", "/api/v1/video/ingress_streams/ingressId", nil, 1)
}
