// Code generated by Fern. DO NOT EDIT.

package tasks

import (
	context "context"
	latticesdkgo "github.com/anduril/lattice-sdk-go"
	core "github.com/anduril/lattice-sdk-go/core"
	internal "github.com/anduril/lattice-sdk-go/internal"
	option "github.com/anduril/lattice-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Submit a request to create a task and schedule it for delivery. Tasks, once delivered, will
// be asynchronously updated by their destined agent.
func (c *Client) CreateTask(
	ctx context.Context,
	request *latticesdkgo.TaskCreation,
	opts ...option.RequestOption,
) (*latticesdkgo.Task, error) {
	response, err := c.WithRawResponse.CreateTask(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetTask(
	ctx context.Context,
	// ID of task to return
	taskID string,
	opts ...option.RequestOption,
) (*latticesdkgo.Task, error) {
	response, err := c.WithRawResponse.GetTask(
		ctx,
		taskID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update the status of a task.
func (c *Client) UpdateTaskStatus(
	ctx context.Context,
	// ID of task to update status of
	taskID string,
	request *latticesdkgo.TaskStatusUpdate,
	opts ...option.RequestOption,
) (*latticesdkgo.Task, error) {
	response, err := c.WithRawResponse.UpdateTaskStatus(
		ctx,
		taskID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Query for tasks by a specified search criteria.
func (c *Client) QueryTasks(
	ctx context.Context,
	request *latticesdkgo.TaskQuery,
	opts ...option.RequestOption,
) (*latticesdkgo.TaskQueryResults, error) {
	response, err := c.WithRawResponse.QueryTasks(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This is a long polling API that will block until a new task is ready for delivery. If no new task is
// available then the server will hold on to your request for up to 5 minutes, after that 5 minute timeout
// period you will be expected to reinitiate a new request.
func (c *Client) ListenAsAgent(
	ctx context.Context,
	request *latticesdkgo.AgentListener,
	opts ...option.RequestOption,
) (*latticesdkgo.AgentRequest, error) {
	response, err := c.WithRawResponse.ListenAsAgent(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
