// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: anduril/taskmanager/v1/generic_spec.pub.proto

package taskmanagerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenericSpec is a wrapper for arbitrary JSON payloads. Meant for wrapping a Task's specification field, if needed.
type GenericSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Can represent any JSON value.
	Payload       *structpb.Value `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericSpec) Reset() {
	*x = GenericSpec{}
	mi := &file_anduril_taskmanager_v1_generic_spec_pub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericSpec) ProtoMessage() {}

func (x *GenericSpec) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_taskmanager_v1_generic_spec_pub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericSpec.ProtoReflect.Descriptor instead.
func (*GenericSpec) Descriptor() ([]byte, []int) {
	return file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDescGZIP(), []int{0}
}

func (x *GenericSpec) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_anduril_taskmanager_v1_generic_spec_pub_proto protoreflect.FileDescriptor

const file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDesc = "" +
	"\n" +
	"-anduril/taskmanager/v1/generic_spec.pub.proto\x12\x16anduril.taskmanager.v1\x1a\x1cgoogle/protobuf/struct.proto\"?\n" +
	"\vGenericSpec\x120\n" +
	"\apayload\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\apayloadB\xf7\x01\n" +
	"\x1acom.anduril.taskmanager.v1B\x13GenericSpecPubProtoP\x01ZJgithub.com/anduril/lattice-sdk-go/src/anduril/taskmanager/v1;taskmanagerv1\xa2\x02\x03ATX\xaa\x02\x16Anduril.Taskmanager.V1\xca\x02\x16Anduril\\Taskmanager\\V1\xe2\x02\"Anduril\\Taskmanager\\V1\\GPBMetadata\xea\x02\x18Anduril::Taskmanager::V1b\x06proto3"

var (
	file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDescOnce sync.Once
	file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDescData []byte
)

func file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDescGZIP() []byte {
	file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDescOnce.Do(func() {
		file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDesc), len(file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDesc)))
	})
	return file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDescData
}

var file_anduril_taskmanager_v1_generic_spec_pub_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_anduril_taskmanager_v1_generic_spec_pub_proto_goTypes = []any{
	(*GenericSpec)(nil),    // 0: anduril.taskmanager.v1.GenericSpec
	(*structpb.Value)(nil), // 1: google.protobuf.Value
}
var file_anduril_taskmanager_v1_generic_spec_pub_proto_depIdxs = []int32{
	1, // 0: anduril.taskmanager.v1.GenericSpec.payload:type_name -> google.protobuf.Value
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anduril_taskmanager_v1_generic_spec_pub_proto_init() }
func file_anduril_taskmanager_v1_generic_spec_pub_proto_init() {
	if File_anduril_taskmanager_v1_generic_spec_pub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDesc), len(file_anduril_taskmanager_v1_generic_spec_pub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anduril_taskmanager_v1_generic_spec_pub_proto_goTypes,
		DependencyIndexes: file_anduril_taskmanager_v1_generic_spec_pub_proto_depIdxs,
		MessageInfos:      file_anduril_taskmanager_v1_generic_spec_pub_proto_msgTypes,
	}.Build()
	File_anduril_taskmanager_v1_generic_spec_pub_proto = out.File
	file_anduril_taskmanager_v1_generic_spec_pub_proto_goTypes = nil
	file_anduril_taskmanager_v1_generic_spec_pub_proto_depIdxs = nil
}
