// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: anduril/tasks/ad/desertguardian/rf/v1/rf_tasks.pub.proto

package rfv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransmitState int32

const (
	TransmitState_TRANSMIT_STATE_INVALID          TransmitState = 0
	TransmitState_TRANSMIT_STATE_TRANSMITTING     TransmitState = 1
	TransmitState_TRANSMIT_STATE_NOT_TRANSMITTING TransmitState = 2
)

// Enum value maps for TransmitState.
var (
	TransmitState_name = map[int32]string{
		0: "TRANSMIT_STATE_INVALID",
		1: "TRANSMIT_STATE_TRANSMITTING",
		2: "TRANSMIT_STATE_NOT_TRANSMITTING",
	}
	TransmitState_value = map[string]int32{
		"TRANSMIT_STATE_INVALID":          0,
		"TRANSMIT_STATE_TRANSMITTING":     1,
		"TRANSMIT_STATE_NOT_TRANSMITTING": 2,
	}
)

func (x TransmitState) Enum() *TransmitState {
	p := new(TransmitState)
	*p = x
	return p
}

func (x TransmitState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransmitState) Descriptor() protoreflect.EnumDescriptor {
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_enumTypes[0].Descriptor()
}

func (TransmitState) Type() protoreflect.EnumType {
	return &file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_enumTypes[0]
}

func (x TransmitState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransmitState.Descriptor instead.
func (TransmitState) EnumDescriptor() ([]byte, []int) {
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescGZIP(), []int{0}
}

type SurveillanceState int32

const (
	SurveillanceState_SURVEILLANCE_STATE_INVALID         SurveillanceState = 0
	SurveillanceState_SURVEILLANCE_STATE_SURVEILLING     SurveillanceState = 1
	SurveillanceState_SURVEILLANCE_STATE_NOT_SURVEILLING SurveillanceState = 2
)

// Enum value maps for SurveillanceState.
var (
	SurveillanceState_name = map[int32]string{
		0: "SURVEILLANCE_STATE_INVALID",
		1: "SURVEILLANCE_STATE_SURVEILLING",
		2: "SURVEILLANCE_STATE_NOT_SURVEILLING",
	}
	SurveillanceState_value = map[string]int32{
		"SURVEILLANCE_STATE_INVALID":         0,
		"SURVEILLANCE_STATE_SURVEILLING":     1,
		"SURVEILLANCE_STATE_NOT_SURVEILLING": 2,
	}
)

func (x SurveillanceState) Enum() *SurveillanceState {
	p := new(SurveillanceState)
	*p = x
	return p
}

func (x SurveillanceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SurveillanceState) Descriptor() protoreflect.EnumDescriptor {
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_enumTypes[1].Descriptor()
}

func (SurveillanceState) Type() protoreflect.EnumType {
	return &file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_enumTypes[1]
}

func (x SurveillanceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SurveillanceState.Descriptor instead.
func (SurveillanceState) EnumDescriptor() ([]byte, []int) {
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescGZIP(), []int{1}
}

type EmissionControlState int32

const (
	EmissionControlState_EMISSION_CONTROL_STATE_INVALID     EmissionControlState = 0
	EmissionControlState_EMISSION_CONTROL_STATE_ALLOWED     EmissionControlState = 1
	EmissionControlState_EMISSION_CONTROL_STATE_NOT_ALLOWED EmissionControlState = 2
)

// Enum value maps for EmissionControlState.
var (
	EmissionControlState_name = map[int32]string{
		0: "EMISSION_CONTROL_STATE_INVALID",
		1: "EMISSION_CONTROL_STATE_ALLOWED",
		2: "EMISSION_CONTROL_STATE_NOT_ALLOWED",
	}
	EmissionControlState_value = map[string]int32{
		"EMISSION_CONTROL_STATE_INVALID":     0,
		"EMISSION_CONTROL_STATE_ALLOWED":     1,
		"EMISSION_CONTROL_STATE_NOT_ALLOWED": 2,
	}
)

func (x EmissionControlState) Enum() *EmissionControlState {
	p := new(EmissionControlState)
	*p = x
	return p
}

func (x EmissionControlState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmissionControlState) Descriptor() protoreflect.EnumDescriptor {
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_enumTypes[2].Descriptor()
}

func (EmissionControlState) Type() protoreflect.EnumType {
	return &file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_enumTypes[2]
}

func (x EmissionControlState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmissionControlState.Descriptor instead.
func (EmissionControlState) EnumDescriptor() ([]byte, []int) {
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescGZIP(), []int{2}
}

// Set the transmit state of an RF Platform such as a Radar, Beacon, or Radio.
type SetTransmitState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransmitState TransmitState          `protobuf:"varint,1,opt,name=transmit_state,json=transmitState,proto3,enum=anduril.tasks.ad.desertguardian.rf.v1.TransmitState" json:"transmit_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTransmitState) Reset() {
	*x = SetTransmitState{}
	mi := &file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTransmitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTransmitState) ProtoMessage() {}

func (x *SetTransmitState) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTransmitState.ProtoReflect.Descriptor instead.
func (*SetTransmitState) Descriptor() ([]byte, []int) {
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescGZIP(), []int{0}
}

func (x *SetTransmitState) GetTransmitState() TransmitState {
	if x != nil {
		return x.TransmitState
	}
	return TransmitState_TRANSMIT_STATE_INVALID
}

// Set the surveillance state of a passive (listen-only) RF Platform.
type SetSurveillanceState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SurveillanceState SurveillanceState      `protobuf:"varint,1,opt,name=surveillance_state,json=surveillanceState,proto3,enum=anduril.tasks.ad.desertguardian.rf.v1.SurveillanceState" json:"surveillance_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetSurveillanceState) Reset() {
	*x = SetSurveillanceState{}
	mi := &file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSurveillanceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSurveillanceState) ProtoMessage() {}

func (x *SetSurveillanceState) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSurveillanceState.ProtoReflect.Descriptor instead.
func (*SetSurveillanceState) Descriptor() ([]byte, []int) {
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescGZIP(), []int{1}
}

func (x *SetSurveillanceState) GetSurveillanceState() SurveillanceState {
	if x != nil {
		return x.SurveillanceState
	}
	return SurveillanceState_SURVEILLANCE_STATE_INVALID
}

// Set whether or not an RF Platform has Emmission Control (EmCon).
// If supported, RF platforms should only expose the SetTransmitState task when EmissionControlState is EMISSION_CONTROL_STATE_ALLOWED.
// When in EMISSION_CONTROL_STATE_NOT_ALLOWED, the Platform should be in TRANSMIT_STATE_NOT_TRANSMITTING, and should remove SetTransmitState from the task Catalog.
type SetEmissionControlState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmconState    EmissionControlState   `protobuf:"varint,1,opt,name=emcon_state,json=emconState,proto3,enum=anduril.tasks.ad.desertguardian.rf.v1.EmissionControlState" json:"emcon_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEmissionControlState) Reset() {
	*x = SetEmissionControlState{}
	mi := &file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEmissionControlState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEmissionControlState) ProtoMessage() {}

func (x *SetEmissionControlState) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEmissionControlState.ProtoReflect.Descriptor instead.
func (*SetEmissionControlState) Descriptor() ([]byte, []int) {
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescGZIP(), []int{2}
}

func (x *SetEmissionControlState) GetEmconState() EmissionControlState {
	if x != nil {
		return x.EmconState
	}
	return EmissionControlState_EMISSION_CONTROL_STATE_INVALID
}

var File_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto protoreflect.FileDescriptor

const file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDesc = "" +
	"\n" +
	"8anduril/tasks/ad/desertguardian/rf/v1/rf_tasks.pub.proto\x12%anduril.tasks.ad.desertguardian.rf.v1\"o\n" +
	"\x10SetTransmitState\x12[\n" +
	"\x0etransmit_state\x18\x01 \x01(\x0e24.anduril.tasks.ad.desertguardian.rf.v1.TransmitStateR\rtransmitState\"\x7f\n" +
	"\x14SetSurveillanceState\x12g\n" +
	"\x12surveillance_state\x18\x01 \x01(\x0e28.anduril.tasks.ad.desertguardian.rf.v1.SurveillanceStateR\x11surveillanceState\"w\n" +
	"\x17SetEmissionControlState\x12\\\n" +
	"\vemcon_state\x18\x01 \x01(\x0e2;.anduril.tasks.ad.desertguardian.rf.v1.EmissionControlStateR\n" +
	"emconState*q\n" +
	"\rTransmitState\x12\x1a\n" +
	"\x16TRANSMIT_STATE_INVALID\x10\x00\x12\x1f\n" +
	"\x1bTRANSMIT_STATE_TRANSMITTING\x10\x01\x12#\n" +
	"\x1fTRANSMIT_STATE_NOT_TRANSMITTING\x10\x02*\x7f\n" +
	"\x11SurveillanceState\x12\x1e\n" +
	"\x1aSURVEILLANCE_STATE_INVALID\x10\x00\x12\"\n" +
	"\x1eSURVEILLANCE_STATE_SURVEILLING\x10\x01\x12&\n" +
	"\"SURVEILLANCE_STATE_NOT_SURVEILLING\x10\x02*\x86\x01\n" +
	"\x14EmissionControlState\x12\"\n" +
	"\x1eEMISSION_CONTROL_STATE_INVALID\x10\x00\x12\"\n" +
	"\x1eEMISSION_CONTROL_STATE_ALLOWED\x10\x01\x12&\n" +
	"\"EMISSION_CONTROL_STATE_NOT_ALLOWED\x10\x02B\xc9\x02\n" +
	")com.anduril.tasks.ad.desertguardian.rf.v1B\x0fRfTasksPubProtoP\x01ZPgithub.com/anduril/lattice-sdk-go/src/anduril/tasks/ad/desertguardian/rf/v1;rfv1\xa2\x02\x05ATADR\xaa\x02%Anduril.Tasks.Ad.Desertguardian.Rf.V1\xca\x02%Anduril\\Tasks\\Ad\\Desertguardian\\Rf\\V1\xe2\x021Anduril\\Tasks\\Ad\\Desertguardian\\Rf\\V1\\GPBMetadata\xea\x02*Anduril::Tasks::Ad::Desertguardian::Rf::V1b\x06proto3"

var (
	file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescOnce sync.Once
	file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescData []byte
)

func file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescGZIP() []byte {
	file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescOnce.Do(func() {
		file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDesc), len(file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDesc)))
	})
	return file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDescData
}

var file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_goTypes = []any{
	(TransmitState)(0),              // 0: anduril.tasks.ad.desertguardian.rf.v1.TransmitState
	(SurveillanceState)(0),          // 1: anduril.tasks.ad.desertguardian.rf.v1.SurveillanceState
	(EmissionControlState)(0),       // 2: anduril.tasks.ad.desertguardian.rf.v1.EmissionControlState
	(*SetTransmitState)(nil),        // 3: anduril.tasks.ad.desertguardian.rf.v1.SetTransmitState
	(*SetSurveillanceState)(nil),    // 4: anduril.tasks.ad.desertguardian.rf.v1.SetSurveillanceState
	(*SetEmissionControlState)(nil), // 5: anduril.tasks.ad.desertguardian.rf.v1.SetEmissionControlState
}
var file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_depIdxs = []int32{
	0, // 0: anduril.tasks.ad.desertguardian.rf.v1.SetTransmitState.transmit_state:type_name -> anduril.tasks.ad.desertguardian.rf.v1.TransmitState
	1, // 1: anduril.tasks.ad.desertguardian.rf.v1.SetSurveillanceState.surveillance_state:type_name -> anduril.tasks.ad.desertguardian.rf.v1.SurveillanceState
	2, // 2: anduril.tasks.ad.desertguardian.rf.v1.SetEmissionControlState.emcon_state:type_name -> anduril.tasks.ad.desertguardian.rf.v1.EmissionControlState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_init() }
func file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_init() {
	if File_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDesc), len(file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_goTypes,
		DependencyIndexes: file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_depIdxs,
		EnumInfos:         file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_enumTypes,
		MessageInfos:      file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_msgTypes,
	}.Build()
	File_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto = out.File
	file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_goTypes = nil
	file_anduril_tasks_ad_desertguardian_rf_v1_rf_tasks_pub_proto_depIdxs = nil
}
