// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: anduril/entitymanager/v1/notification.pub.proto

package entitymanagerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A notification to indicate when a field is overridden on an entity.
type OverrideNotificationPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entity containing the values to override and the entityID being overriden.
	// Used by the client to determine the value a field is overridden to (e.g. hostile).
	Entity *Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	// The field path determining the path on an entity to override. Used by the client
	// to determine whether an override request was for a particular field (e.g. disposition).
	FieldPath string `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// The provenance of the override request. This should always match the OverrideEntityRequest
	// provenance field.
	Provenance    *Provenance `protobuf:"bytes,3,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideNotificationPayload) Reset() {
	*x = OverrideNotificationPayload{}
	mi := &file_anduril_entitymanager_v1_notification_pub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideNotificationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideNotificationPayload) ProtoMessage() {}

func (x *OverrideNotificationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_entitymanager_v1_notification_pub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideNotificationPayload.ProtoReflect.Descriptor instead.
func (*OverrideNotificationPayload) Descriptor() ([]byte, []int) {
	return file_anduril_entitymanager_v1_notification_pub_proto_rawDescGZIP(), []int{0}
}

func (x *OverrideNotificationPayload) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *OverrideNotificationPayload) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *OverrideNotificationPayload) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

var File_anduril_entitymanager_v1_notification_pub_proto protoreflect.FileDescriptor

const file_anduril_entitymanager_v1_notification_pub_proto_rawDesc = "" +
	"\n" +
	"/anduril/entitymanager/v1/notification.pub.proto\x12\x18anduril.entitymanager.v1\x1a)anduril/entitymanager/v1/entity.pub.proto\"\xbc\x01\n" +
	"\x1bOverrideNotificationPayload\x128\n" +
	"\x06entity\x18\x01 \x01(\v2 .anduril.entitymanager.v1.EntityR\x06entity\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tR\tfieldPath\x12D\n" +
	"\n" +
	"provenance\x18\x03 \x01(\v2$.anduril.entitymanager.v1.ProvenanceR\n" +
	"provenanceB\x86\x02\n" +
	"\x1ccom.anduril.entitymanager.v1B\x14NotificationPubProtoP\x01ZNgithub.com/anduril/lattice-sdk-go/src/anduril/entitymanager/v1;entitymanagerv1\xa2\x02\x03AEX\xaa\x02\x18Anduril.Entitymanager.V1\xca\x02\x18Anduril\\Entitymanager\\V1\xe2\x02$Anduril\\Entitymanager\\V1\\GPBMetadata\xea\x02\x1aAnduril::Entitymanager::V1b\x06proto3"

var (
	file_anduril_entitymanager_v1_notification_pub_proto_rawDescOnce sync.Once
	file_anduril_entitymanager_v1_notification_pub_proto_rawDescData []byte
)

func file_anduril_entitymanager_v1_notification_pub_proto_rawDescGZIP() []byte {
	file_anduril_entitymanager_v1_notification_pub_proto_rawDescOnce.Do(func() {
		file_anduril_entitymanager_v1_notification_pub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anduril_entitymanager_v1_notification_pub_proto_rawDesc), len(file_anduril_entitymanager_v1_notification_pub_proto_rawDesc)))
	})
	return file_anduril_entitymanager_v1_notification_pub_proto_rawDescData
}

var file_anduril_entitymanager_v1_notification_pub_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_anduril_entitymanager_v1_notification_pub_proto_goTypes = []any{
	(*OverrideNotificationPayload)(nil), // 0: anduril.entitymanager.v1.OverrideNotificationPayload
	(*Entity)(nil),                      // 1: anduril.entitymanager.v1.Entity
	(*Provenance)(nil),                  // 2: anduril.entitymanager.v1.Provenance
}
var file_anduril_entitymanager_v1_notification_pub_proto_depIdxs = []int32{
	1, // 0: anduril.entitymanager.v1.OverrideNotificationPayload.entity:type_name -> anduril.entitymanager.v1.Entity
	2, // 1: anduril.entitymanager.v1.OverrideNotificationPayload.provenance:type_name -> anduril.entitymanager.v1.Provenance
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_anduril_entitymanager_v1_notification_pub_proto_init() }
func file_anduril_entitymanager_v1_notification_pub_proto_init() {
	if File_anduril_entitymanager_v1_notification_pub_proto != nil {
		return
	}
	file_anduril_entitymanager_v1_entity_pub_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anduril_entitymanager_v1_notification_pub_proto_rawDesc), len(file_anduril_entitymanager_v1_notification_pub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anduril_entitymanager_v1_notification_pub_proto_goTypes,
		DependencyIndexes: file_anduril_entitymanager_v1_notification_pub_proto_depIdxs,
		MessageInfos:      file_anduril_entitymanager_v1_notification_pub_proto_msgTypes,
	}.Build()
	File_anduril_entitymanager_v1_notification_pub_proto = out.File
	file_anduril_entitymanager_v1_notification_pub_proto_goTypes = nil
	file_anduril_entitymanager_v1_notification_pub_proto_depIdxs = nil
}
