// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: anduril/type/geometry.pub.proto

package _type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A 2d grid with binary values for each grid cell.
type Grid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bottom left extent of the 2d grid. This represents the
	// farthest corner on the grid cell, not the center of the
	// grid cell.
	BottomLeftPos *LLA `protobuf:"bytes,1,opt,name=bottom_left_pos,json=bottomLeftPos,proto3" json:"bottom_left_pos,omitempty"`
	// The top right extent of the 2d grid. This represents the
	// farthest corner on the grid cell, not the center of the
	// grid cell.
	TopRightPos *LLA `protobuf:"bytes,2,opt,name=top_right_pos,json=topRightPos,proto3" json:"top_right_pos,omitempty"`
	// The width of the grid in number of cells.
	GridWidth uint32 `protobuf:"varint,3,opt,name=grid_width,json=gridWidth,proto3" json:"grid_width,omitempty"`
	// The height of the grid in number of cells.
	GridHeight uint32 `protobuf:"varint,4,opt,name=grid_height,json=gridHeight,proto3" json:"grid_height,omitempty"`
	// Stores the cell values. Each byte contains 8 bits representing
	// binary values of cells. Cells are unravelled in row-major order,
	// with the first cell located at the top-left corner of the grid.
	// In a single byte, the smallest bit represents the left most cell.
	CellValues    []byte `protobuf:"bytes,5,opt,name=cell_values,json=cellValues,proto3" json:"cell_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid) Reset() {
	*x = Grid{}
	mi := &file_anduril_type_geometry_pub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid) ProtoMessage() {}

func (x *Grid) ProtoReflect() protoreflect.Message {
	mi := &file_anduril_type_geometry_pub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid.ProtoReflect.Descriptor instead.
func (*Grid) Descriptor() ([]byte, []int) {
	return file_anduril_type_geometry_pub_proto_rawDescGZIP(), []int{0}
}

func (x *Grid) GetBottomLeftPos() *LLA {
	if x != nil {
		return x.BottomLeftPos
	}
	return nil
}

func (x *Grid) GetTopRightPos() *LLA {
	if x != nil {
		return x.TopRightPos
	}
	return nil
}

func (x *Grid) GetGridWidth() uint32 {
	if x != nil {
		return x.GridWidth
	}
	return 0
}

func (x *Grid) GetGridHeight() uint32 {
	if x != nil {
		return x.GridHeight
	}
	return 0
}

func (x *Grid) GetCellValues() []byte {
	if x != nil {
		return x.CellValues
	}
	return nil
}

var File_anduril_type_geometry_pub_proto protoreflect.FileDescriptor

const file_anduril_type_geometry_pub_proto_rawDesc = "" +
	"\n" +
	"\x1fanduril/type/geometry.pub.proto\x12\fanduril.type\x1a\x1danduril/type/coords.pub.proto\"\xd9\x01\n" +
	"\x04Grid\x129\n" +
	"\x0fbottom_left_pos\x18\x01 \x01(\v2\x11.anduril.type.LLAR\rbottomLeftPos\x125\n" +
	"\rtop_right_pos\x18\x02 \x01(\v2\x11.anduril.type.LLAR\vtopRightPos\x12\x1d\n" +
	"\n" +
	"grid_width\x18\x03 \x01(\rR\tgridWidth\x12\x1f\n" +
	"\vgrid_height\x18\x04 \x01(\rR\n" +
	"gridHeight\x12\x1f\n" +
	"\vcell_values\x18\x05 \x01(\fR\n" +
	"cellValuesB\xa9\x01\n" +
	"\x10com.anduril.typeB\x10GeometryPubProtoP\x01Z2github.com/anduril/lattice-sdk-go/src/anduril/type\xa2\x02\x03ATX\xaa\x02\fAnduril.Type\xca\x02\fAnduril\\Type\xe2\x02\x18Anduril\\Type\\GPBMetadata\xea\x02\rAnduril::Typeb\x06proto3"

var (
	file_anduril_type_geometry_pub_proto_rawDescOnce sync.Once
	file_anduril_type_geometry_pub_proto_rawDescData []byte
)

func file_anduril_type_geometry_pub_proto_rawDescGZIP() []byte {
	file_anduril_type_geometry_pub_proto_rawDescOnce.Do(func() {
		file_anduril_type_geometry_pub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anduril_type_geometry_pub_proto_rawDesc), len(file_anduril_type_geometry_pub_proto_rawDesc)))
	})
	return file_anduril_type_geometry_pub_proto_rawDescData
}

var file_anduril_type_geometry_pub_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_anduril_type_geometry_pub_proto_goTypes = []any{
	(*Grid)(nil), // 0: anduril.type.Grid
	(*LLA)(nil),  // 1: anduril.type.LLA
}
var file_anduril_type_geometry_pub_proto_depIdxs = []int32{
	1, // 0: anduril.type.Grid.bottom_left_pos:type_name -> anduril.type.LLA
	1, // 1: anduril.type.Grid.top_right_pos:type_name -> anduril.type.LLA
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_anduril_type_geometry_pub_proto_init() }
func file_anduril_type_geometry_pub_proto_init() {
	if File_anduril_type_geometry_pub_proto != nil {
		return
	}
	file_anduril_type_coords_pub_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anduril_type_geometry_pub_proto_rawDesc), len(file_anduril_type_geometry_pub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anduril_type_geometry_pub_proto_goTypes,
		DependencyIndexes: file_anduril_type_geometry_pub_proto_depIdxs,
		MessageInfos:      file_anduril_type_geometry_pub_proto_msgTypes,
	}.Build()
	File_anduril_type_geometry_pub_proto = out.File
	file_anduril_type_geometry_pub_proto_goTypes = nil
	file_anduril_type_geometry_pub_proto_depIdxs = nil
}
